#!/usr/bin/env python3
"""Build the SmartQuest caption track and sidecar SRT from video-plan.json.

Captions never live inside the lesson scenes. They are one transparent Manim
track composited by ffmpeg, so fixing a typo never re-renders the mathematics,
and the sidecar .srt comes out of the same data for free.

    python3 build_captions.py --plan video-plan.json --out-dir src

Writes:
    <out-dir>/captions.py     a Manim scene named CaptionTrack
    out/subtitles.srt         sidecar for YouTube
    (stdout)                  the pacing report

Then:
    manim -r 1920,1080 --fps 60 -t --format=mov src/captions.py CaptionTrack
    ffmpeg -y -i out/picture.mp4 -i <track>.mov \
      -filter_complex "[0:v][1:v]overlay=0:0" -c:v libx264 -crf 18 \
      -pix_fmt yuv420p out/picture-subbed.mp4

Exits non-zero if any cue breaks the pacing contract, so it can gate a build.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

MAX_CPS = 4.0        # 字/秒, Latin word counted as 2 字
MIN_CUE = 2.0        # seconds a cue must stay on screen
MAX_LINE = 24        # 全形字 per line
LATIN = re.compile(r"[A-Za-z][A-Za-z''\-]*")


def weight(text: str) -> int:
    """Reading weight in 全形字. A Latin word costs 2; CJK and punctuation cost 1."""
    latin_words = LATIN.findall(text)
    stripped = LATIN.sub("", text)
    cjk = len([c for c in stripped if not c.isspace()])
    return cjk + 2 * len(latin_words)


def srt_time(t: float) -> str:
    ms = int(round(t * 1000))
    h, ms = divmod(ms, 3600000)
    m, ms = divmod(ms, 60000)
    s, ms = divmod(ms, 1000)
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


def collect(plan: dict) -> list[dict]:
    cues = []
    for shot in plan["shots"]:
        for cue in shot.get("subtitles", []):
            cues.append({**cue, "shot": shot["id"],
                         "shotStart": shot["start"], "shotEnd": shot["end"]})
    cues.sort(key=lambda c: c["start"])
    return cues


def check(plan: dict, cues: list[dict]) -> list[str]:
    problems = []
    for c in cues:
        dur = c["end"] - c["start"]
        w = weight(c["text"])
        if dur < MIN_CUE - 1e-9:
            problems.append(f'{c["shot"]} {c["start"]:.2f}s: cue is {dur:.2f}s, '
                            f'minimum is {MIN_CUE:.1f}s — "{c["text"][:20]}…"')
        if dur > 0 and w / dur > MAX_CPS + 1e-9:
            problems.append(f'{c["shot"]} {c["start"]:.2f}s: {w} 字 in {dur:.2f}s '
                            f'= {w/dur:.2f} 字/秒, limit {MAX_CPS} — needs {w/MAX_CPS:.2f}s')
        if c["start"] < c["shotStart"] - 1e-6 or c["end"] > c["shotEnd"] + 1e-6:
            problems.append(f'{c["shot"]} {c["start"]:.2f}s: cue escapes its shot '
                            f'[{c["shotStart"]:.2f}, {c["shotEnd"]:.2f}]')
        if "\n" in c["text"]:                       # author-chosen line breaks
            for line in c["text"].split("\n"):
                if weight(line) > MAX_LINE:
                    problems.append(f'{c["shot"]} {c["start"]:.2f}s: line is '
                                    f'{weight(line)} 字, limit {MAX_LINE}')
            if len(c["text"].split("\n")) > 2:
                problems.append(f'{c["shot"]} {c["start"]:.2f}s: more than 2 lines')
        elif w > 2 * MAX_LINE:                      # will be auto-wrapped to 2 lines
            problems.append(f'{c["shot"]} {c["start"]:.2f}s: {w} 字 will not fit two '
                            f'lines of {MAX_LINE} — split the cue')
    for a, b in zip(cues, cues[1:]):
        if b["start"] < a["end"] - 1e-6:
            problems.append(f'cues overlap: {a["shot"]} ends {a["end"]:.2f}s, '
                            f'{b["shot"]} starts {b["start"]:.2f}s')

    # per-shot narration room
    for shot in plan["shots"]:
        span = shot["end"] - shot["start"]
        spoken = sum(c["end"] - c["start"] for c in shot.get("subtitles", []))
        still = shot.get("stillSeconds")
        if still is not None and still < span * 0.25 - 1e-6:
            problems.append(f'{shot["id"]}: stillSeconds {still:.1f} < 25% of {span:.1f}s')
        if spoken > span * 0.9 + 1e-6:
            problems.append(f'{shot["id"]}: subtitles fill {spoken:.1f}s of {span:.1f}s '
                            f'— no room for the teacher to breathe')
    return problems


SCENE_TEMPLATE = '''"""GENERATED by build_captions.py — do not hand-edit.

Source of truth: {plan_name}
Render transparent, then composite:

    manim -r {w},{h} --fps {fps} -t --format=mov captions.py CaptionTrack
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import numpy as np
from manim import *
from smartquest_theme import sync_frame, Stage, fit_caption

sync_frame()

CUES = {cues!r}


class CaptionTrack(Scene):
    def construct(self):
        st = Stage()
        self.camera.background_color = "#00000000"
        max_w = st.w - 2 * st.margin
        t = 0.0
        for start, end, text, terms in CUES:
            if start > t:
                self.wait(start - t)
            # Fixed size for every cue; wraps to two balanced lines when needed
            # and NEVER scales. If something still overflows, the pacing gate in
            # build_captions.py should have rejected the cue.
            cap = fit_caption(text, terms, max_w)
            cap.move_to(np.array([0.0, st.caption_bottom + cap.height / 2, 0.0]))
            self.add(cap)
            self.wait(end - start)
            self.remove(cap)
            t = end
        if {duration!r} > t:
            self.wait({duration!r} - t)
'''


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--plan", required=True)
    ap.add_argument("--out-dir", default="src")
    ap.add_argument("--srt", default="out/subtitles.srt")
    ap.add_argument("--allow-pacing-failures", action="store_true",
                    help="write the files even if the pacing contract is broken")
    args = ap.parse_args()

    plan_path = Path(args.plan)
    plan = json.loads(plan_path.read_text())
    cues = collect(plan)
    if not cues:
        print("No subtitles found in the plan — nothing to build.", file=sys.stderr)
        return 1

    problems = check(plan, cues)
    print(f"{len(cues)} cues across {len(plan['shots'])} shots")
    for c in cues:
        d = c["end"] - c["start"]
        w = weight(c["text"])
        print(f'  {c["shot"]:<5} {c["start"]:7.3f}-{c["end"]:7.3f}  '
              f'{w:>3} 字 / {d:5.2f}s = {w/d:4.2f} 字/秒   {c["text"][:34]}')
    if problems:
        print(f"\n{len(problems)} pacing problem(s):", file=sys.stderr)
        for p in problems:
            print(f"  ✗ {p}", file=sys.stderr)
        if not args.allow_pacing_failures:
            print("\nFix the plan, or re-run with --allow-pacing-failures.", file=sys.stderr)
            return 2
    else:
        print("\npacing contract: all cues pass")

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    scene = SCENE_TEMPLATE.format(
        plan_name=plan_path.name, w=plan["width"], h=plan["height"], fps=plan["fps"],
        cues=[(c["start"], c["end"], c["text"], list(c.get("terms", []))) for c in cues],
        duration=float(plan["durationSeconds"]))
    (out_dir / "captions.py").write_text(scene)

    srt_path = Path(args.srt)
    srt_path.parent.mkdir(parents=True, exist_ok=True)
    srt_path.write_text("".join(
        f"{i}\n{srt_time(c['start'])} --> {srt_time(c['end'])}\n{c['text']}\n\n"
        for i, c in enumerate(cues, 1)))

    print(f"\nwrote {out_dir / 'captions.py'}")
    print(f"wrote {srt_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
