"""Scaffold a new song's edit from its analysis: app/src/timeline-<id>.ts + docs/TREATMENT-<id>.md

    python3 scaffold_song.py --song <id> --from 29.3 --to 45.8        # a clip: one plate per lyric line in it
    python3 scaffold_song.py --song <id> --section chorus1            # the same, for one analysed section
    python3 scaffold_song.py --song <id> --full                       # the whole song, one plate per line

Plain Python (no deps): run it from anywhere inside the repo. It never overwrites an existing file.

The timeline cuts each plate on the last beat at/before the plate's first sung word (exactly how the
P(doom) edit and the 11:59 test clip cut), so every cut is on the beat and before the singing. The
treatment skeleton carries every number a scene author needs — word start times, downbeats, the drum
drop(s), the plate windows — so nobody retypes timings by hand. The creative sections are left as TODO
for the lead to write.
"""
import argparse, json, re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ap = argparse.ArgumentParser()
ap.add_argument("--song", required=True)
g = ap.add_mutually_exclusive_group(required=True)
g.add_argument("--from", dest="t0", type=float)
g.add_argument("--section")
g.add_argument("--full", action="store_true")
ap.add_argument("--to", dest="t1", type=float)
A = ap.parse_args()

L = json.loads((ROOT / "data" / A.song / "lyrics.json").read_text())["lines"]
AU = json.loads((ROOT / "data" / A.song / "audio.json").read_text())
beats, downs = AU["beats"], AU["downbeats"]

if A.full:
    t0, t1 = 0.0, AU["duration"]
elif A.section:
    sec = next((s for s in AU["sections"] if s["name"] == A.section), None)
    if not sec:
        raise SystemExit(f"no section {A.section}; have: {', '.join(s['name'] for s in AU['sections'])}")
    t0, t1 = sec["start"], sec["end"]
else:
    if A.t1 is None:
        raise SystemExit("--from needs --to")
    t0, t1 = A.t0, A.t1

# lines whose first word is sung inside the clip (a pickup just before t0 still counts: 1 s grace)
lines = [l for l in L if t0 - 1.0 <= l["words"][0]["start"] < t1]
if not lines:
    raise SystemExit(f"no sung line starts in {t0:.2f}-{t1:.2f}")


def beat_before(t, tol=0.02):
    return max((b for b in beats if b <= t + tol), default=beats[0])


def down_at_or_after(t):
    return next((d for d in downs if d >= t - 0.02), AU["duration"])


def slug(text, taken):
    base = re.sub(r"[^a-z0-9]+", "", (text.split() or ["plate"])[0].lower())[:10] or "plate"
    s, k = base, 2
    while s in taken:
        s, k = f"{base}{k}", k + 1
    taken.add(s)
    return s


taken = set()
plates = []
for i, l in enumerate(lines):
    start = beat_before(l["words"][0]["start"])
    if i == 0:  # a lead-in: start on the last downbeat before the first word (the bar the pickup sits in)
        start = max((d for d in downs if d <= l["words"][0]["start"] - 0.05), default=0.0)
    plates.append(dict(id=slug(l["text"], taken), line=l, start=round(start, 3)))
for p, q in zip(plates, plates[1:]):
    p["end"] = q["start"]
plates[-1]["end"] = round(down_at_or_after(max(lines[-1]["end"] + 0.3, t1)), 3)

# drum drops: from the analysis notes if present
drops = re.findall(r"drum re-entries \[([^\]]*)\]", AU.get("notes", ""))
drop_list = [float(x) for x in drops[0].split(",")] if drops and drops[0].strip() else []

tl = ROOT / "app" / "src" / f"timeline-{A.song}.ts"
tr = ROOT / "docs" / f"TREATMENT-{A.song}.md"
for f in (tl, tr):
    if f.exists():
        raise SystemExit(f"{f} exists; not overwriting (delete it or pick another --song)")

esc = lambda s: s.replace("\\", "\\\\").replace("'", "\\'")
query = lambda text: " ".join(text.split()[:4])  # first words are enough for lyrics.get()
fold = lambda t: t.lower().replace("\u2018", "'").replace("\u2019", "'").replace("\u201c", '"').replace("\u201d", '"')  # = lyrics.ts fold()
nth = {}
entries, cuts = [], []
for p in plates:
    q = query(p["line"]["text"])
    k = sum(1 for l in L[: p["line"]["i"]] if fold(q) in fold(l["text"]))  # nth match, as Lyrics.get(q, nth)
    nth[p["id"]] = k
    cuts.append(f"    {p['id']}: cut('{esc(q)}', {k}),")
entries = [f"    E('{p['id']}', '{p['id']}', b.{p['id']}, {('b.' + plates[i + 1]['id']) if i + 1 < len(plates) else 'b.end'}),"
           for i, p in enumerate(plates)]
first_lead = plates[0]["start"]
tl.write_text(f"""// The edit for ?song={A.song}: one plate per lyric line. Generated by analysis/scaffold_song.py —
// boundaries are anchored to lyric lines and snapped to the beat grid; edit freely.
import type {{ TimelineEntry }} from './engine/engine';
import type {{ SceneClass }} from './engine/scene';
import type {{ Lyrics }} from './engine/lyrics';
import type {{ AudioData }} from './engine/audio';

const modules = import.meta.glob<{{ default: SceneClass }}>('./scenes/{A.song}/*.ts');
const scene = (name: string) => () => {{
  const m = modules[`./scenes/{A.song}/${{name}}.ts`];
  return m ? m() : Promise.reject(new Error(`scene module not found: scenes/{A.song}/${{name}}.ts`));
}};

export function makeTimeline(ly: Lyrics, au: AudioData): TimelineEntry[] {{
  /** Cut on the last beat at/before the first word of the matching line. */
  const cut = (q: string, nth = 0, tol = 0.02) => {{
    const s = ly.get(q, nth).words[0]!.start;
    return au.timeOfBeat(Math.floor(au.beatAt(s + tol)));
  }};
  /** First downbeat at/after t. */
  const bar = (t: number) => au.downbeats.find((d) => d >= t - 0.02) ?? au.duration;

  const b = {{
{chr(10).join(cuts)}
    end: bar({plates[-1]['end'] - 0.01:.2f}),
  }};
  b.{plates[0]['id']} = Math.min(b.{plates[0]['id']}, {first_lead:.3f}); // lead-in

  const E = (id: string, file: string, start: number, end: number, extra: Partial<TimelineEntry> = {{}}): TimelineEntry =>
    ({{ id, load: scene(file), start, end, ...extra }});

  return [
{chr(10).join(entries)}
  ];
}}
""")

words_md = "\n".join(
    f"- `{p['line']['text']}`: " + ", ".join(f"{w['w']} {w['start']:.2f}" for w in p["line"]["words"])
    + (f" (held to ~{p['line']['end']:.1f})" if p is plates[-1] else "") for p in plates)
dl = [d for d in downs if plates[0]["start"] - 0.01 <= d <= plates[-1]["end"] + 0.01]
drops_in = [d for d in drop_list if plates[0]["start"] - 0.5 <= d <= plates[-1]["end"]]
rows = "\n".join(f"| `{p['id']}` | `scenes/{A.song}/{p['id']}.ts` | {p['start']:.2f} → {p['end']:.2f} | {p['line']['text']} |" for p in plates)
render_from = max(0.0, plates[0]['line']['words'][0]['start'] - 0.3)
render_to = min(AU['duration'], plates[-1]['line']['end'] + 0.4)
tr.write_text(f"""# Song {A.song} — treatment

TODO one paragraph: the song, the idea in one sentence (a single concept every plate belongs to, like
"plates from an illustrated treatise"), and the running motif that travels through every plate.

Preview: `http://localhost:5173/?song={A.song}&t={render_from:.1f}`. Renders: add `--song {A.song}` to every
`render.ts` command. Clip: **{render_from:.1f} → {render_to:.1f} s** ({render_to - render_from:.1f} s).

## Style (inherits `docs/TREATMENT.md`)

TODO — or keep the P(doom) system: read its *Tone*, *Palette*, *Typography* and *Karaoke rules*. Whatever
you choose, state: the palette (≤ 3 colours + 1 accent, which one blooms), the type roles, the motion
rules (cuts on downbeats, hits on kicks, strong eases then holds), the humour register, a **not-slop**
list (no neon cyberpunk, glowing brains, code rain, particle nebulae, lens-flare soup, stock "AI"
imagery), and **originality** (no logos, no imitations of real product UIs, no copyrighted characters).

## Timing (seconds, from `data/{A.song}/*.json` — look lines up by content in code, never hard-code)

{words_md}
- Downbeats: {', '.join(f'{d:.2f}' for d in dl)}. Beat period {AU['beat_period']:.4f} s ({AU['bpm']:.2f} BPM).
- Drum drop(s) (drums re-enter after silence, on a downbeat): {', '.join(f'{d:.2f}' for d in drops_in) or 'none in this clip'}.
- Kicks: `f.a.kick`, `audio.events('kick', t0, t1)`.

## Plates

| id | file | window | line |
|---|---|---|---|
{rows}

""" + "\n".join(f"""### `{p['id']}` — TODO title
TODO: what the frame is (one concrete visual idea, a pun on the line, not a literal illustration);
how every word of `{p['line']['text']}` becomes part of the image and lights exactly on its time;
what happens on each downbeat/kick; the camera (push, tilt, whip, snap); the one deadpan detail;
how it hands off to the next plate.
""" for p in plates))

print("wrote", tl.relative_to(ROOT))
print("wrote", tr.relative_to(ROOT))
print(f"plates: " + ", ".join(f"{p['id']} {p['start']:.2f}-{p['end']:.2f}" for p in plates))
print(f"render the clip with: --from {render_from:.2f} --to {render_to:.2f}")
